# Array


|함수         | 	설명|
|:-----------|:---------|
|eltype(A)   |	A 의 원소 타입|
|length(A)   |	A 의 원소 갯수| 
|ndims(A)    |	A 의 차원수|
|size(A)     |	A 의 크기 튜플|
|size(A,n)   |	A 의 n 차원의 크기|
|axes(A)     |	A 의 유효한 인덱스 튜플|
|axes(A,n)   |	A 의 유효 인덱스 n차원 범위(range)|
|eachindex(A)|	A 의 모든 위치를 방문하는 효율적인 반복자(iterator)|
|stride(A,k) |	k 차원 방향의 스트라이드 (연속한 원소 간의 선형 인덱스 거리)|
|strides(A)  |	모든 차원의 스트라이드 튜플|

## 생성과 초기화

|함수|	설명|
|:--- |:--- |
|Array{T}(undef, dims...)|	초기화 되지 않은 밀집 Array|
|zeros(T, dims...)|	모든 값이 0으로 초기화 된 Array|
|ones(T, dims...)|	모든 값이 1로 초기화 된 Array|
|trues(dims...)|	모든 값이 true로 초기화 된 BitArray|
|falses(dims...)|	모든 값이 false로 초기화 된 BitArray|
|reshape(A, dims...)|	A 와 동일한 데이타를 가지고 있지만 형상이 다른 배열|
|copy(A)|	A 의 얕은 복사|
|deepcopy(A)|	A 의 깊은 복사 (모든 원소를 재귀적으로 복사함)|
|similar(A, T, dims...)|	A 와 동일한 종류(밀집, 희소, 등)의 초기화 되지 않은 배열. 지정된 원소 타입과 형상을 가짐. 두번째와 세번째 인수는 선택적이며, 기본값은 A의 원소타입과 차원이다.|
|reinterpret(T, A)|	A 와 동일한 이진 데이터를 가지고 있지만, 원소 타입이 T 인 배열|
|rand(T, dims...)|	독립 동일하며 열린구간 \[0,1)상에서 연속 균일 분포를 가진 랜덤 Array|
|randn(T, dims...)|	독립 동일하며 표준 정규 분포를 가진 랜덤 Array|
|Matrix{T}(I, m, n)|	크기가 m × n 인 단위 행렬|
|range(start, stop=stop, length=n)|	start에서 stop까지 n 개의 원소가 선형적으로 배치된 구간|
|fill!(A, x)|	배열 A 를 x 값으로 채우기|
|fill(x, dims...)|	x 값으로 차 있는 Array|

In [18]:
zeros(Int8,2,3)

2×3 Matrix{Int8}:
 0  0  0
 0  0  0

In [20]:
zeros(Int8,(2,3))

2×3 Matrix{Int8}:
 0  0  0
 0  0  0

In [21]:
zeros(2,3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [22]:
vcat([1, 2], 3)

3-element Vector{Int64}:
 1
 2
 3

In [24]:
hcat([1 2], 3)

1×3 Matrix{Int64}:
 1  2  3

In [1]:
[[1; 2]; [3, 4]]

4-element Vector{Int64}:
 1
 2
 3
 4

In [2]:
[[1 2] [3 4]]

1×4 Matrix{Int64}:
 1  2  3  4

In [3]:
[[1 2]; [3 4]]

2×2 Matrix{Int64}:
 1  2
 3  4

In [4]:
[[1;2;];[3;4;]]

4-element Vector{Int64}:
 1
 2
 3
 4

In [11]:
x= rand(8)

8-element Vector{Float64}:
 0.6225644932737155
 0.5357023288053997
 0.5150649849125241
 0.6321006197406154
 0.27323982064155894
 0.3742796690600446
 0.2724426447862015
 0.9435054573325868

In [12]:
[ 0.25*x[i-1] + 0.5*x[i] + 0.25*x[i+1] for i=2:length(x)-1 ]

6-element Vector{Float64}:
 0.5522585339492597
 0.5494832295927659
 0.5131265112588285
 0.38821498252094444
 0.3235604508869624
 0.4656676039912586

In [13]:
Float32[ 0.25*x[i-1] + 0.5*x[i] + 0.25*x[i+1] for i=2:length(x)-1 ]

6-element Vector{Float32}:
 0.55225855
 0.54948324
 0.5131265
 0.38821498
 0.32356045
 0.4656676

In [14]:
sum(1/n^2 for n=1:1000)

1.6439345666815615

In [17]:
map(tuple, (1/(i+j) for i=1:2, j=1:2), [1 3 ; 2 4])

2×2 Matrix{Tuple{Float64, Int64}}:
 (0.5, 1)       (0.333333, 3)
 (0.333333, 2)  (0.25, 4)

In [19]:
[ (i,j) for i=1:3 for j=1:i]

6-element Vector{Tuple{Int64, Int64}}:
 (1, 1)
 (2, 1)
 (2, 2)
 (3, 1)
 (3, 2)
 (3, 3)

In [20]:
[ (i,j) for i=1:3 for j=1:i if i+j == 4]

2-element Vector{Tuple{Int64, Int64}}:
 (2, 2)
 (3, 1)

## 인덱싱

In [21]:
A= reshape(collect(1:16), (2,2,2,2))

2×2×2×2 Array{Int64, 4}:
[:, :, 1, 1] =
 1  3
 2  4

[:, :, 2, 1] =
 5  7
 6  8

[:, :, 1, 2] =
  9  11
 10  12

[:, :, 2, 2] =
 13  15
 14  16

In [22]:
A[1,2,1,1]

3

In [23]:
A[[1,2],[1],[1,2],[1]]

2×1×2×1 Array{Int64, 4}:
[:, :, 1, 1] =
 1
 2

[:, :, 2, 1] =
 5
 6

In [24]:
A[[1,2],[1],[1,2],1]

2×1×2 Array{Int64, 3}:
[:, :, 1] =
 1
 2

[:, :, 2] =
 5
 6

In [25]:
A[[1 2; 1 2]]

2×2 Matrix{Int64}:
 1  2
 1  2

In [26]:
A[[1 2; 1 2],1,2,1]

2×2 Matrix{Int64}:
 5  6
 5  6

In [28]:
x = collect(reshape(1:9, 3, 3))

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [32]:
x[3,3]=-9
x[1:2,1:2]=[-1  -4 ; -2 -5]
x

3×3 Matrix{Int64}:
 -1  -4   7
 -2  -5   8
  3   6  -9

## 직교 인덱스(Cartesian indices)

In [35]:
A = reshape(1:32, 4, 4, 2);
A

4×4×2 reshape(::UnitRange{Int64}, 4, 4, 2) with eltype Int64:
[:, :, 1] =
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

[:, :, 2] =
 17  21  25  29
 18  22  26  30
 19  23  27  31
 20  24  28  32

In [36]:
A[3,2,1]

7

In [37]:
A[CartesianIndex(3,2,1)] ==A[3,2,1]==7

true

In [38]:
page = A[:,:,1]

4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [39]:
page[[CartesianIndex(1,1),
             CartesianIndex(2,2),
             CartesianIndex(3,3),
             CartesianIndex(4,4)]]

4-element Vector{Int64}:
  1
  6
 11
 16

## 논리 인덱싱

In [40]:
x = reshape(1:16,4,4)

4×4 reshape(::UnitRange{Int64}, 4, 4) with eltype Int64:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [41]:
x[[false,true,true,false],:]

2×4 Matrix{Int64}:
 2  6  10  14
 3  7  11  15

In [42]:
x[[2,3],:]

2×4 Matrix{Int64}:
 2  6  10  14
 3  7  11  15

In [43]:
mask= map(ispow2,x)

4×4 Matrix{Bool}:
 1  0  0  0
 1  0  0  0
 0  0  0  0
 1  1  0  1

In [44]:
A = rand(4,3);
B = view(A, 1:3, 2:3);
println(A)
println(B)

[0.4992727589070719 0.46245363606356205 0.43181950430955773; 0.48800775487901826 0.09049143961642037 0.7009032469508479; 0.4729589052004942 0.9587092972065467 0.8548123406690247; 0.9704754701527049 0.3794029569253402 0.08455747499169142]
[0.46245363606356205 0.43181950430955773; 0.09049143961642037 0.7009032469508479; 0.9587092972065467 0.8548123406690247]


In [46]:
for i in eachindex(B)
    @show i
end

i = CartesianIndex(1, 1)
i = CartesianIndex(2, 1)
i = CartesianIndex(3, 1)
i = CartesianIndex(1, 2)
i = CartesianIndex(2, 2)
i = CartesianIndex(3, 2)


In [47]:
a = rand(2,1); A = rand(2,3);
println(a)
println(A)

[0.32670730609119814; 0.7801338322989575;;]
[0.7629621270808935 0.6486527675717206 0.40221060667656305; 0.8407165904618318 0.11356630967262937 0.3025065906078329]


In [48]:
repeat(a,1,3)+A

2×3 Matrix{Float64}:
 1.08967  0.97536  0.728918
 1.62085  0.8937   1.08264

In [49]:
convert.(Float32, [1, 2])

2-element Vector{Float32}:
 1.0
 2.0

In [50]:
string.(1:3, ". ", ["First", "Second", "Third"])

3-element Vector{String}:
 "1. First"
 "2. Second"
 "3. Third"